### ISSUE TITLE
Test the current cylc conda package

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-conda#1]
Up for grabs, see current README for instructions, or issue in cylc-admin https://github.com/cylc/cylc-admin/issues/27

**Comment by sadielbartholomew** [comment]
@kinow, I've just run through the instructions under 'Testing' in the README & everything runs fine! Various commands for ``cylc``, ``cylc-uiserver`` & ``isodatetime`` worked as expected after creating a fresh environment & installing only the ``cylc`` super-package. So it seems the basic Cylc 8 conda package works, great job! I'll close this accordingly.

(BTW I did notice one minor typo in the README instructions, so I'll put in a trivial PR to amend that.)

**Comment by kinow** [comment]
Thanks Sadie! Relieved it worked on another computer.
