### ISSUE TITLE
List packages in alphabetical order

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-conda#6]
From https://github.com/cylc/cylc-conda/pull/5#issue-310564079

>I was wondering if it would perhaps be sensible to list packages under such sections in alphabetical order (or perhaps those with definitive version ranges listed alphabetically, then those without alphabetically, or similar) to make it easier to pick out packages, & prevent any duplication in future, when lists may be extended?

**Comment by kinow** [comment]
+1 for @sadielbartholomew 's suggestion

**Comment by sadielbartholomew** [comment]
I'll get this done today as it is a quick & simple Issue to tackle.
